openapi: 3.0.1
info:
  title: Todo-Listen-Verwaltung
  description: ""
  contact:
    email: andreashehmann2@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.1
servers:
- url: http://127.0.0.1:5000/
tags:
- name: Listenverwaltung Listen
- name: Listenverwaltung Einträge
paths:
  /todo-list/{list_id}/entries:
    get:
      tags:
      - Listenverwaltung Einträge
      summary: Liefert alle Einträge einer Todo-Liste zurück.
      operationId: getListEntries
      parameters:
      - name: list_id
        in: path
        description: ID der gewünschten Liste
        required: true
        schema:
          type: string
      responses:
        200:
          description: Liste zurückgeliefert
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoEntry'
        404:
          description: falsche ID
          content: {}
        405:
          description: falsche Methode verwendet
          content: {}
        500:
          description: Fehler im Server
          content: {}
  /todo-list/{list_id}:
    delete:
      tags:
      - Listenverwaltung Listen
      summary: Löscht eine komplette Todo-Liste mit allen Einträgen.
      operationId: deleteList
      parameters:
      - name: list_id
        in: path
        description: ID der gewünschten Liste
        required: true
        schema:
          type: string
      responses:
        200:
          description: Liste gelöscht
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/success'
        404:
          description: falsche ID
          content: {}
        405:
          description: falsche Methode verwendet
          content: {}
        500:
          description: Fehler im Server
          content: {}
    get:
      tags:
      - Listenverwaltung Listen
      summary: Liefert eine spezifische Todo-Liste zurück.
      operationId: getList
      parameters:
      - name: list_id
        in: path
        description: ID der gewünschten Liste
        required: true
        schema:
          type: string
      responses:
        200:
          description: Liste zurückgeliefert
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoEntry'
        404:
          description: falsche ID
          content: {}
        405:
          description: falsche Methode verwendet
          content: {}
        500:
          description: Fehler im Server
          content: {}
  /todo-list:
    post:
      tags:
      - Listenverwaltung Listen
      summary: Erstellt eine neue Todo-Liste.
      operationId: createList
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoList'
      responses:
        200:
          description: Liste erstellt
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/TodoEntry'
        400:
          description: falsche ID
          content: {}
        405:
          description: falsche Methode verwendet
          content: {}
        500:
          description: Fehler im Server
          content: {}
  /todo-list/{list_id}/entry:
    post:
      tags:
      - Listenverwaltung Einträge
      summary: Fügt einen Eintrag zu einer bestehenden Todo-Liste hinzu.
      operationId: addEntry
      parameters:
      - name: list_id
        in: path
        description: ID der gewünschten Liste
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoEntry'
      responses:
        200:
          description: Liste zurückgeliefert
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoEntry'
        404:
          description: falsche ID
          content: {}
        405:
          description: falsche Methode verwendet
          content: {}
        500:
          description: Fehler im Server
          content: {}
  /todo-lists:
    get:
      tags:
      - Listenverwaltung Listen
      summary: Liefert alle Todo-Listen zurück.
      operationId: getAllLists
      responses:
        200:
          description: Listen zurückgeliefert
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoEntry'
        405:
          description: falsche Methode verwendet
          content: {}
        500:
          description: Fehler im Server
          content: {}
components:
  schemas:
    TodoList:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    TodoEntry:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
